apiVersion: runtime.madgrape.com/v1alpha1
kind: NoSQLDb
metadata:
  namespace: crossplane-system
  name: nosqltestdb
  annotations:
    crossplane.io/external-name: nosqltestdb
spec:
  parameters:
    location: westus
    resourceGroup: crossplanetest
    partitionKeyPath: /id
    providerConfigName: default
  writeConnectionSecretToRef:
    name: nosqltestdb-connection-details
